// ⚠️  GENERATO da tools/gen-dice.mjs — non modificare a mano.
// Ogni stringa = un dado (6 facce). 'q' = faccia "Qu" (Q+U inseparabili).
// Tre livelli di difficoltà: distribuzione di vocali e consonanti diverse.

import type { GridSize } from './types.js';
import type { Difficulty } from './difficulty.js';

export const DICE_4_EASY: readonly string[] = [
  'leeima',
  'iluitl',
  'nnlotr',
  'ogmtdc',
  'eeumuu',
  'irreil',
  'vvbmrr',
  'omouos',
  'aoovgd',
  'urorob',
  'tfocra',
  'ourned',
  'sfuouo',
  'roucsp',
  'cienni',
  'alnfas',
];

export const DICE_4_NORMAL: readonly string[] = [
  'eomrna',
  'abtoer',
  'eohetp',
  'navuqe',
  'enanes',
  'napioi',
  'otiaso',
  'rvtrei',
  'lnsrcd',
  'icvfrf',
  'hootjp',
  'aodrhv',
  'ntrgrt',
  'auevzt',
  'cotssa',
  'mcdell',
];

export const DICE_4_HARD: readonly string[] = [
  'bnhsst',
  'mstioo',
  'lusczu',
  'epiica',
  'ggcuci',
  'ahtisu',
  'glooaz',
  'tuvidm',
  'tlnglp',
  'nmvoaa',
  'gnhsrf',
  'xcqvde',
  'urailm',
  'sacpnr',
  'rmmass',
  'pgrxuq',
];

export const DICE_5_EASY: readonly string[] = [
  'ubbore',
  'oeefeu',
  'enartt',
  'rcictd',
  'uotltr',
  'eorsnu',
  'sriiil',
  'cueser',
  'sfosou',
  'ntacao',
  'euvmva',
  'nnugrr',
  'gspnvd',
  'asasei',
  'itispa',
  'msltag',
  'lsoeec',
  'geeufo',
  'slronu',
  'uigigt',
  'oculao',
  'rpovni',
  'urgdle',
  'liiili',
  'iioorr',
];

export const DICE_5_NORMAL: readonly string[] = [
  'qteeen',
  'ouolrd',
  'hfteci',
  'reogvt',
  'nzfqes',
  'gcsuol',
  'ozspie',
  'nasimu',
  'nvarcg',
  'rfetsi',
  'sarcnt',
  'ruthbo',
  'hoacst',
  'rrrisr',
  'eduuir',
  'ittilm',
  'cdatsi',
  'ruvuop',
  'nutnhs',
  'ianvpo',
  'sueufi',
  'omaepv',
  'smlbce',
  'tountt',
  'poiogu',
];

export const DICE_5_HARD: readonly string[] = [
  'ruhlur',
  'cgqmla',
  'tauzae',
  'rovnmh',
  'cmflsl',
  'nistkz',
  'seldqv',
  'rbfmzc',
  'soxepc',
  'ystrrj',
  'nemgzb',
  'vdmanm',
  'vnogvp',
  'euaisw',
  'osdhcr',
  'ruedzv',
  'hrtnae',
  'ewyipi',
  'tnsgco',
  'qttnas',
  'sierko',
  'edueir',
  'cloitm',
  'atarni',
  'aorate',
];

export const DICE_6_EASY: readonly string[] = [
  'eaaoci',
  'reoarn',
  'ovriul',
  'tvutsr',
  'mltnpn',
  'obsseo',
  'regona',
  'vuleet',
  'ucutte',
  'ctooca',
  'adtaic',
  'reotod',
  'siimoi',
  'utctte',
  'umbmpt',
  'eibndo',
  'cuiobt',
  'mntpto',
  'urtsrr',
  'meiirr',
  'evaoeo',
  'lturbe',
  'soiiom',
  'eeovri',
  'bussau',
  'alcblc',
  'nuruas',
  'ootiuo',
  'nmvrbc',
  'uomrec',
  'irzeao',
  'orpeop',
  'iricre',
  'vsegup',
  'upritu',
  'mtulss',
];

export const DICE_6_NORMAL: readonly string[] = [
  'gtsslc',
  'ierbci',
  'nuetiz',
  'ruruda',
  'tsithv',
  'nabioi',
  'uoesod',
  'ircoot',
  'sunasm',
  'iruoea',
  'roqnps',
  'mustmu',
  'rasrtt',
  'ttrfnu',
  'tnvotd',
  'ptunoi',
  'onozni',
  'aaesnx',
  'ioimig',
  'tocasv',
  'hmrvqs',
  'atrmgt',
  'eometl',
  'matusu',
  'rtrpsn',
  'saltas',
  'tbiive',
  'rttrre',
  'qlouoa',
  'thvhen',
  'urspre',
  'soeagi',
  'uvearp',
  'ntprrc',
  'attein',
  'sopunu',
];

export const DICE_6_HARD: readonly string[] = [
  'itrasg',
  'onhrnc',
  'deodiu',
  'foqyrc',
  'oevtgn',
  'uutroi',
  'angnqf',
  'ogshbi',
  'qsisog',
  'huaupb',
  'ullvre',
  'uvslht',
  'ssvmni',
  'gapgcp',
  'narnht',
  'otdaei',
  'ittgnb',
  'farrvu',
  'rbtchm',
  'nvmibl',
  'nhsohq',
  'rbhret',
  'onurnu',
  'roascq',
  'engsav',
  'uarzvg',
  'odsutb',
  'scvdhs',
  'esnqeg',
  'geaofe',
  'ifxzst',
  'raglii',
  'btpdvh',
  'auctes',
  'orpsqs',
  'etsrti',
];

/** Mappa dimensione → difficoltà → set di dadi. */
export const DICE: Record<GridSize, Record<Difficulty, readonly string[]>> = {
  4: { facile: DICE_4_EASY, normale: DICE_4_NORMAL, difficile: DICE_4_HARD },
  5: { facile: DICE_5_EASY, normale: DICE_5_NORMAL, difficile: DICE_5_HARD },
  6: { facile: DICE_6_EASY, normale: DICE_6_NORMAL, difficile: DICE_6_HARD },
};
